import { EmailNotification, Record } from '@servicenow/sdk/core'

const eventTable = 'sysevent_register' as any
Record({ $id: Now.ID['ai-control-event-review-needed'], table: eventTable, data: { event_name: 'global.ai_control.review_needed', table: 'u_sn_spec_version', fired_by: 'SnAiControlService.submit', priority: 100, description: 'AI control review needed' } })
Record({ $id: Now.ID['ai-control-event-changes-requested'], table: eventTable, data: { event_name: 'global.ai_control.changes_requested', table: 'u_sn_spec_version', fired_by: 'SnAiControlService.requestChanges', priority: 100, description: 'AI control changes requested' } })
// One event, not three. A reported failure and a worker that went silent leave the record
// in the same state and are resolved the same way — by a human deciding to retry — so they
// do not earn separate templates. `job_succeeded` is gone: a success advances the phase,
// which is already visible, and mailing somebody about it was noise.
Record({ $id: Now.ID['ai-control-event-build-attention'], table: eventTable, data: { event_name: 'global.ai_control.build_attention', table: 'u_sn_enhancement', fired_by: 'SnAiControlService.finishBuild / ageOutStaleBuilds', priority: 100, description: 'AI control build needs a human decision' } })

EmailNotification({ $id: Now.ID['ai-control-notify-review'], name: 'AI control: spec waiting for review', table: 'u_sn_spec_version', active: true, triggerConditions: { generationType: 'event', eventName: 'global.ai_control.review_needed' }, recipientDetails: { recipientFields: ['u_authored_by'], eventParm1WithRecipient: true, eventParm2WithRecipient: true, sendToCreator: false }, emailContent: { subject: 'AI control: spec awaits review', messageHtml: '<p>Open ${URI_REF} to review the exact content hash and authority state.</p>' } })
EmailNotification({ $id: Now.ID['ai-control-notify-changes'], name: 'AI control: changes requested', table: 'u_sn_spec_version', active: true, triggerConditions: { generationType: 'event', eventName: 'global.ai_control.changes_requested' }, recipientDetails: { recipientFields: ['u_authored_by'], eventParm1WithRecipient: true, eventParm2WithRecipient: true, sendToCreator: false }, emailContent: { subject: 'AI control: changes requested', messageHtml: '<p>Open ${URI_REF} for the attributed review note and create a new draft version.</p>' } })
EmailNotification({ $id: Now.ID['ai-control-notify-build-attention'], name: 'AI control: build needs a decision', table: 'u_sn_enhancement', active: true, triggerConditions: { generationType: 'event', eventName: 'global.ai_control.build_attention' }, recipientDetails: { recipientFields: ['opened_by'], eventParm1WithRecipient: true, eventParm2WithRecipient: true, sendToCreator: false }, emailContent: { subject: 'AI control: build stopped and needs a decision', messageHtml: '<p>Open ${URI_REF}. The evidence summary says whether the build reported a failure or its worker went silent. Retrying is a human decision.</p>' } })
